swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /registration:
    x-swagger-router-controller: hello_world
    post:
      tags:
        - User
      description: Registers a user
      operationId: registration
      parameters:
        - name: registrationDTO
          in: body
          schema:
            $ref: '#/definitions/RegistrationDTO'
      responses:
        "200":
          description: Sikeres regisztráció
          schema:
            $ref: '#/definitions/UserDTO'
  /user/{id}:
    x-swagger-router-controller: hello_world
    get:
      tags:
        - User
      description: Returns a user's data
      operationId: getUser
      parameters:
        - name: id
          in: path
          description: 'userid'
          required: true
          type: number
      responses:
        "200":
          description: sikeres user lekérés
          schema:
            $ref: '#/definitions/UserDTO'
  /users:
    x-swagger-router-controller: hello_world
    get:
      tags:
        - User
      operationId: getUsers
      responses:
        "200":
          description: user lista lekeres
          schema:
            type: array
            items:
              $ref: '#/definitions/UserDTO'




# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  RegistrationDTO:
    properties:
      name:
        type: string
      password:
        type: string
      email:
        type: string
      gender:
        type: number
      birthName:
        type: string
      interest:
        type: number
  UserDTO:
    required:
      - name
    properties:
      id:
        type: number
      name:
        type: string
      email:
        type: string
      gender:
        type: number
      birthName:
        type: string